openapi: 3.0.0
servers:
  - url: https://apis-pix-hml.a55scd.com
info:
  title: Microcash Auth
  version: 1.0.0
  description: Endpoint to obtain OAuth2 token for Pix API client credentials.
paths:
  /pix/oauth2/token:
    post:
      summary: Obtain OAuth2 Token
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                grant_type:
                  type: string
                  enum:
                    - client_credentials
                  example: client_credentials
                client_id:
                  type: string
                  example: '{clientid}'
                client_secret:
                  type: string
                  example: '{clientsecret}'
      responses:
        '200':
          description: Successful response containing OAuth2 token
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    example: eyJraWQ…
                  expires_in:
                    type: integer
                    example: 3600
                  token_type:
                    type: string
                    example: Bearer
        '400':
          description: Bad request if parameters are incorrect or missing
        '401':
          description: Unauthorized if client credentials are invalid
x-readme:
  explorer-enabled: true
  proxy-enabled: true
